version: "3.3"
services:
  swagger-api:
    image: danielgtaylor/apisprout
    ports:
      - "8000:8000"
    volumes:
      - ./api.yaml:/api.yaml
    command: /api.yaml --watch

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./api.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8002:8080"
